# Generated by Django 3.1.5 on 2021-03-02 05:20

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210209_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.ImageField(blank=True, null=True, upload_to=apps.blog.models.UploadPostImagesPath('sm'))),
                ('large', models.ImageField(blank=True, null=True, upload_to=apps.blog.models.UploadPostImagesPath('lg'))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Posts Images',
            },
        ),
    ]
